import "./globals.css";
import Header from "./components/Header";
import SessionProvider from "./components/AuthComponents/SessionProviderWraper";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
        {/* TourCraft Script - Correct way in Next.js */}
        <Script
          src="https://tour-craft-v2-6u9h.vercel.app/tours.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
