import "./globals.css";
import Header from "./components/Header";
import SessionProvider from "./components/AuthComponents/SessionProviderWraper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* TourCraft Script - Add this */}
        <script
          src="https://bowblogs.vercel.app/tour.js?key=dev-api-key"
          async
        ></script>
      </head>
      <body>
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
